environment:
  YARN_IGNORE_ENGINES: true

  matrix:
    - nodejs_version: "9"
    - nodejs_version: "8"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - yarn test

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"

build: off
deploy: off
