name: Release
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  release:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Checkout the repository
          uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          with:
            persist-credentials: false
        - name: Clean npm package
          uses: ai/copy-changelog-to-release@a6dc825c34575add2da2060796794f7b84894628 # v0.2.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
